stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py 
    deps: 
    - src/data/data_ingestion.py
    params: 
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps: 
    - data/interim
    - src/features/feature_engineering.py
    params: 
    - feature_engineering.max_features 
    outs: 
    - data/processed 
  
  model_building:
    cmd: python src/model/model_building.py 
    deps:
    - src/model/model_building.py
    - data/processed
    outs:
    - model/model.pkl 

  model_evaluation: 
    cmd: python src/model/model_evaluation.py 
    deps: 
    - model/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json 
    outs:
    - reports/experiment_info.json

  model_registeration:
    cmd: python src/model/model_registeration.py
    deps:
    - reports/experiment_info.json
    - src/model/model_registeration.py
  
    